export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_USER_OPTIMISTIC = 'DELETE_USER_OPTIMISTIC';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const KEEP_SIGNED_SUCCESS = 'KEEP_SIGNED_SUCCESS';
export const LOGOUT = 'LOGOUT';

// UTILS
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_TOPBAR_MOBILE = 'TOGGLE_TOPBAR_MOBILE';
export const TOGGLE_MENU_MOBILE = 'TOGGLE_MENU_MOBILE';
